### ISSUE TITLE
🛑 Zanshin API health check is down

### ISSUE THREAD

**Issue by tenchisecurity** [tenchi-security/zanshin_status#47]
In [`8a15d97`](https://github.com/tenchi-security/zanshin_status/commit/8a15d9762c283714d980dbda6f3265ad088c3f46
), Zanshin API health check (https://api.zanshin.tenchisecurity.com/ping) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by edpin** [comment]
No issue has been found. Temporary infrastructure hiccup.
